### PR TITLE
Recipe for Lua

### PR DESCRIPTION
**Pull request by ids1024**
Ideally, the build system implemented in `environ.sh` in the `libc` repo should be properly integrated into the cookbook.

### CODE REVIEW

**Comment by ids1024** [comment]
I think it might be better if the recipe system was Makefile-based instead of bash-based. (Which I guess would be like BSD ports, though I haven't used BSD much).

**Comment by jackpot51** [comment]
Thanks! It is good to see what is required, I hope we can adjust the cookbook to make C packaging easy as well

**Comment by jackpot51** [comment]
Maybe have a patches directory, where they are iterated one by one in alphanumeric order?

**Comment by jackpot51** [comment]
if [ -d patches ] then for patch in patches/* ...

**Comment by ids1024** [comment]
Since the package already has it's own directory, I think a patches directory is unnecessary. Perhaps just loop over files with a `.patch` suffix? (`for patch in *.patch`...)

**Comment by jackpot51** [comment]
Sure, that is fine

**Comment by jackpot51** [comment]
I am removing the patches, preferring it to be done in the recipe_update step

**Comment by jackpot51** [comment]
I cleaned it up and merged. To follow standards and allow git ignore, I have named the tar file source.tar, and I used strip-components to extract it without the top name

**Comment by jackpot51** [comment]
We can write a tag file for each step and the version that step was completed at, which will make it easy to run steps as needed

**Comment by jackpot51** [comment]
You can `sudo pkg install lua` now

I haven't checked if it works though

**Comment by ids1024** [comment]
> I haven't checked if it works though

A simple test Lua script runs. The repl opens, but doesn't seem to be accepting input; I don't know why.

**Pull request merged**
