### PR TITLE
Add update-all.sh script to rebuild only out of date packages

### PR DESCRIPTION
**Pull request by ids1024**
Something like this is necessary in order for the cookbook to replace the Makefiles in the `redox` repo.

### CODE REVIEW

**Comment by ids1024** [comment]
Although I guess for the build in the `redox` repo, you want to build only some packages (those that are part of the base system).

**Comment by jackpot51** [comment]
Fucking awesome. I will merge asap and use on static.redox-os.org

**Comment by ids1024** [comment]
I've thought of  a potential issue. If a build fails, but a package is present from a previous build of a previous version, it will assume that the package is up to date.

The correct solution is to store version metadata in the package tar. The easy solution is to just remove the `stage.tar` before trying to build.

**Comment by jackpot51** [comment]
sounds good. I have made changes to use fetch instead of update, as it is more correct. Also added publishing of packages at the end.

**Pull request merged**
