### PR TITLE
Add dosbox recipe

### PR DESCRIPTION
**Pull request by xTibor**
Video, mouse, r/w mounting folders, config file management works with small glitches around. Keyboard input doesn't work properly yet, dosbox incorrectly shifts the keycodes around. The `autoxec.bat` section of the config file could be used to run commands until I fix that bug.

### CODE REVIEW

**Comment by jackpot51** [comment]
:1st_place_medal: OMG OMG OMG OMG :1st_place_medal:

**Comment by xTibor** [comment]
```ini
[sdl]
usescancodes=false
```

This change in the config file fixes the keyboard. I'll see how can I make this default on Redox.

**Comment by jackpot51** [comment]
Awesome

**Comment by xTibor** [comment]
Here's the not so awesome part:

```
Z:\>mount s sys:/
```

Running this command in dosbox kills Redox.

**Comment by jackpot51** [comment]
great to find things like this

**Pull request merged**
