### PR TITLE
Add rustual-boy recipe

### PR DESCRIPTION
**Pull request by xTibor**
This pull request adds a recipe for [Rustual Boy](https://github.com/emu-rs/rustual-boy), a Virtual Boy video game emulator. Some minimal changes had to be made to get it compile and run: I updated some dependencies and added a temporary null audio driver.

[Screenshot](https://user-images.githubusercontent.com/1627292/27997060-6c23aa3c-64f0-11e7-9b57-f74d9f3b450b.png)

### CODE REVIEW

**Comment by ids1024** [comment]
Nice! It should be possible to get sound working soon; we have an Intel HD audio driver, but no mixer yet.

**Comment by xTibor** [comment]
Ping for @yupferris, he might like this.

**Comment by yupferris** [comment]
hey NICE! really happy to see this! :)

**Comment by yupferris** [comment]
Also re the changes specific to rustual boy, I'd be happy to merge some of these into upstream. Particularly the null audio sink should be part of the middleware or something ideally. Feel free to open a PR and we can discuss it there :)

**Comment by xTibor** [comment]
Cpal's null audio driver [returns `None` for the list of available endpoints](https://github.com/tomaka/cpal/blob/0245754cd0d5939ec80940197ef6bebfea26bfcc/src/null/mod.rs#L35-L37) and [has `unreachable!()` in `get_supported_formats_list`](https://github.com/tomaka/cpal/blob/0245754cd0d5939ec80940197ef6bebfea26bfcc/src/null/mod.rs#L44-L48) that you're [using and unwrapping](https://github.com/emu-rs/rustual-boy/blob/01ef27a12872328dc93cf86420793061da7b2a88/rustual-boy-cli/src/cpal_driver.rs#L103-L108) in your Cpal driver. So using that driver Rustual Boy cannot get an audio device and cannot query its supported formats. It was just easier to entirely circumvent that code until Redox gets a mixer and a proper Cpal port.

**Comment by yupferris** [comment]
Aha, I see. It's a bit unfortunate though that the fork has to be maintained and kept up to date separately from the main repo. But I suppose that's temporary anyways.

**Pull request merged**
